# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Code origionally written by https://www.coletiv.com/blog/android-github-actions-setup/
name: Basic Test

on:
  push:
    branches: [ test ]

defaults:
  run:
    working-directory: ./app


jobs:
  testing:
    name: Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      # Setup Java JDK
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Step 2: Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      # Step 3: Check the code with Android linter
      - name: Run Android Linter
        run: ./gradlew lintStagingDebug

      # Step 4: Run unit tests
      - name: Run Unit Tests
        run: ./gradlew testStagingDebugUnitTest


