# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Code origionally written by https://www.coletiv.com/blog/android-github-actions-setup/
#name: Basic Test

#on:
#  push:
#    branches: [ test ]

#defaults:
#  run:
#    working-directory: ./app


name: Manually triggered workflow
on: [workflow_dispatch]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello World!"
        echo "- in Home!"