# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# Code origionally written by https://www.coletiv.com/blog/android-github-actions-setup/
#name: Basic Test

#on:
#  push:
#    branches: [ test ]

#defaults:
#  run:
#    working-directory: ./app


name: Manually triggered workflow
on:
  workflow_dispatch:
    branches: [ test ]
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"